name: Publish Workflow

on:
  push:
    branches: ['main']

jobs:
  publish-pipeline:
    name: 'Publish-pipeline'
    runs-on: ubuntu-latest
    steps:
      - name: âœ… Checkout
        uses: actions/checkout@v5
      - name: ğŸ  Setup Node
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          registry-url: 'https://registry.npmjs.org'
      - name: âš™ï¸ Install dependencies
        run: npm ci
      - name: ğŸ‘·ğŸ½ Build Package
        run: npm run build
      - name: ğŸš€ Publish to npm
        run: npm publish --provenance --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
